[package]
name = "kernel_device"
version = "0.1.0"
edition = "2024"

[dependencies]
kernel_physical_memory = { path = "../kernel_physical_memory" }
spin.workspace = true
thiserror.workspace = true

[target.'cfg(target_arch = "x86_64")'.dependencies]
x86_64.workspace = true
