[package]
name = "gpio_demo"
version = "0.1.0"
edition = "2021"

[dependencies]
minilib = { path = "../minilib" }
kernel_abi = { path = "../../kernel/crates/kernel_abi" }

[profile.release]
panic = "abort"
lto = true
codegen-units = 1
