[package]
name = "kernel_virtual_memory"
version = "0.1.0"
edition = "2024"

[dependencies]
log.workspace = true
thiserror.workspace = true

[target.'cfg(target_arch = "x86_64")'.dependencies]
x86_64.workspace = true
